/**
 * @author Yako
 */
export enum Genres {
    Action = "Acción",
    MartialArts = "Artes Marciales",
    Adventure = "Aventuras",
    Racing = "Carreras",
    ScienceFiction = "Ciencia Ficción",
    Comedy = "Comedia",
    Dementia = "Demencia",
    Demons = "Demonios",
    Sports = "Deportes",
    Drama = "Drama",
    Ecchi = "Ecchi",
    School = "Escolares",
    Space = "Espacial",
    Fantasy = "Fantasía",
    Harem = "Harem",
    Historical = "Histórico",
    Kids = "Infantil",
    Josei = "Josei",
    Games = "Juegos",
    Magic = "Magia",
    Mecha = "Mecha",
    Military = "Militar",
    Mystery = "Misterio",
    Music = "Música",
    Parody = "Parodia",
    Police = "Policía",
    Psychological = "Psicológico",
    SliceOfLife = "Recuentos de la vida",
    Romance = "Romance",
    Samurai = "Samurai",
    Seinen = "Seinen",
    Shoujo = "Shoujo",
    Shounen = "Shounen",
    Supernatural = "Sobrenatural",
    Superpowers = "Superpoderes",
    Suspense = "Suspenso",
    Horror = "Terror",
    Vampires = "Vampiros",
    Yaoi = "Yaoi",
    Yuri = "Yuri",
  }